apiVersion: v1
kind: ConfigMap
metadata:
  name: qmstr-config
  namespace: default
data:
  qmstrConfig: |-
    project:
      name: "CI"
      metadata:
        message: "Hello World!"
      server:
        dbAddress: "dgraph:9080"
        rpcAddress: "localhost:50051" # master address
      analysis:
        - analyzer: scancode-analyzer
          name: "Scancode Analyzer"
          config:
            workdir: "/var/qmstr/buildroot"
            resultfile: "/var/qmstr/buildroot/scancode.json"
    #       cached: "true"
